// educationData.js

export const boards10th = [
  "Central Board of Secondary Education (CBSE)",
  "Indian Certificate of Secondary Education (ICSE)",
  "Maharashtra State Board of Secondary and Higher Secondary Education (MSBSHSE)",
  "Uttar Pradesh Madhyamik Shiksha Parishad (UPMSP)",
  "West Bengal Board of Secondary Education (WBBSE)",
  "Bihar School Examination Board (BSEB)",
  "Haryana Board of School Education (HBSE)",
  "Karnataka Secondary Education Examination Board (KSEEB)",
  "Tamil Nadu Board of Secondary Education",
  "Gujarat Secondary and Higher Secondary Education Board (GSEB)",
  "Rajasthan Board of Secondary Education (RBSE)",
  "Madhya Pradesh Board of Secondary Education (MPBSE)",
  "Others"
];

export const streams12th = [
  "Science",
  "Commerce",
  "Arts"
];

export const graduateDegrees = [
  "B.Sc. (Bachelor of Science) – 3 years",
  "B.Tech / B.E. (Bachelor of Technology / Engineering) – 4 years",
  "MBBS (Bachelor of Medicine & Surgery) – 5.5 years",
  "BDS (Bachelor of Dental Surgery) – 5 years",
  "B.Sc. (Nursing), B.Pharm (Pharmacy), BPT (Physiotherapy)",
  "B.Com (Bachelor of Commerce) – 3 years",
  "BBA (Bachelor of Business Administration) – 3 years",
  "BBM (Bachelor of Business Management)",
  "BFIA (Finance & Investment Analysis)",
  "CA, CS, CMA – Professional certifications",
  "B.A. (Bachelor of Arts) – 3 years",
  "BFA (Fine Arts), BPA (Performing Arts)",
  "BSW (Social Work)",
  "LLB (Law) – 5-year integrated course after 12th (BA LLB / BBA LLB)",
  "B.Arch (Architecture) – 5 years",
  "B.Des (Design) – Fashion, Interior, Product Design",
  "BHM (Hotel Management)",
  "B.Ed (Bachelor of Education) – After graduation",
  "B.Plan (Urban & Regional Planning)"
];

export const postgraduateDegrees = [
  "M.Sc. (Master of Science) – 2 years",
  "M.Tech / M.E. (Master of Technology / Engineering) – 2 years",
  "MCA (Master of Computer Applications) – 2 years",
  "M.Pharma (Master of Pharmacy)",
  "M.Stat / M.Math (for Statistics/Math)",
  "M.Com (Master of Commerce) – 2 years",
  "MBA (Master of Business Administration) – 2 years",
  "PGDM (Post Graduate Diploma in Management)",
  "MFC (Master of Finance & Control)",
  "M.A. (Master of Arts) – 2 years",
  "MSW (Master of Social Work)",
  "MFA (Fine Arts), MPA (Performing Arts)",
  "M.Ed (Master of Education)",
  "LL.M (Master of Laws) – 1 to 2 years",
  "MD (Doctor of Medicine) / MS (Master of Surgery) – after MBBS",
  "MDS (Master of Dental Surgery)",
  "MPT (Master of Physiotherapy)",
  "MPH (Master of Public Health)",
  "M.Sc. Nursing",
  "M.S. (Research) – Offered by IITs, IISc"
];

export const diplomaOptions = [
  "Diploma in Civil Engineering",
  "Diploma in Mechanical Engineering",
  "Diploma in Electrical Engineering",
  "Diploma in Computer Science & Engineering",
  "Diploma in Electronics & Communication Engineering",
  "Diploma in Automobile Engineering",
  "Diploma in Information Technology",
  "Diploma in Mechatronics",
  "Diploma in Nursing (GNM)",
  "Diploma in Medical Laboratory Technology (DMLT)",
  "Diploma in Radiology",
  "Diploma in Pharmacy (D.Pharm)",
  "Diploma in Physiotherapy",
  "Diploma in Dental Hygienist",
  "Diploma in Operation Theatre Technology",
  "Diploma in Business Management",
  "Diploma in Financial Accounting",
  "Diploma in Marketing Management",
  "Diploma in Human Resource Management",
  "Diploma in Export-Import Management",
  "Diploma in Banking and Finance",
  "Diploma in Fashion Designing",
  "Diploma in Interior Designing",
  "Diploma in Graphic Designing",
  "Diploma in Animation and Multimedia",
  "Diploma in Film & Television Production",
  "Diploma in Photography",
  "Diploma in Computer Applications",
  "Diploma in Software Engineering",
  "Diploma in Web Designing",
  "Diploma in Cybersecurity",
  "Diploma in Data Science",
  "Diploma in Networking and Hardware",
  "Diploma in Hotel Management",
  "Diploma in Tourism Management",
  "Diploma in Food Production",
  "Diploma in Travel and Tourism"
];

export const phdOptions = [
  "PhD in Physics",
  "PhD in Chemistry",
  "PhD in Mathematics",
  "PhD in Biology / Life Sciences",
  "PhD in Environmental Science",
  "PhD in Computer Science & Engineering",
  "PhD in Electronics & Communication",
  "PhD in Mechanical Engineering",
  "PhD in Civil Engineering",
  "PhD in Biotechnology",
  "PhD in Information Technology",
  "PhD in Commerce",
  "PhD in Finance",
  "PhD in Marketing",
  "PhD in Human Resource Management",
  "PhD in Business Administration / Management",
  "PhD in Economics",
  "PhD in Accounting",
  "PhD in History",
  "PhD in Political Science",
  "PhD in Sociology",
  "PhD in Psychology",
  "PhD in Philosophy",
  "PhD in Geography",
  "PhD in English Literature",
  "PhD in Linguistics",
  "PhD in Education",
  "PhD in Social Work",
  "PhD in Anthropology",
  "PhD in Constitutional Law",
  "PhD in Criminal Law",
  "PhD in International Law",
  "PhD in Corporate Law",
  "PhD in Human Rights Law",
  "PhD in Medicine",
  "PhD in Pharmacy",
  "PhD in Nursing",
  "PhD in Public Health",
  "PhD in Biotechnology and Genetics",
  "PhD in Electrical Engineering",
  "PhD in Computer Engineering",
  "PhD in Aerospace Engineering",
  "PhD in Chemical Engineering",
  "PhD in Material Science",
  "PhD in Environmental Studies",
  "PhD in Data Science / Artificial Intelligence / Machine Learning",
  "PhD in Nanotechnology",
  "PhD in Robotics",
  "PhD in Cybersecurity",
  "PhD in Media Studies / Mass Communication",
  "PhD in Gender Studies",
  "PhD in Urban Planning"
];
